### ISSUE TITLE
请问下BaseApiImpl中的initAssets空方法有用吗?

### ISSUE THREAD

**Issue by CodeIdeal** [caiyonglong/MusicApi#1]
另外拿到的songUrl怎么才能播放呀?我把它传到exoplayer中报403错误

**Comment by caiyonglong** [comment]
1、initAssets：没有用
2、你拿到对的songUrl ，可以复制出来在浏览器中访问，看看是否能够正常访问，因为有时会因为api限制了，所以无法访问

**Comment by CodeIdeal** [comment]
> 1、initAssets：没有用
> 2、你拿到对的songUrl ，可以复制出来在浏览器中访问，看看是否能够正常访问，因为有时会因为api限制了，所以无法访问

嗯嗯,昨天看了下API返回的url和直接在web中访问的音乐资源链接的区别就host有点不同,拿到url后直接替换下web上用的host就ok了  
另,感谢你的开源O(∩_∩)O

**Comment by zhougy0717** [comment]
这个项目的API一定要像Music Lake里一样，借助于http://musiclake.leanapp.cn提供的API service来请求服务吗？
还是通过app.native.js直接访问各个音乐服务的？
请指教，谢谢

**Comment by caiyonglong** [comment]
> 这个项目的API一定要像Music Lake里一样，借助于[http://musiclake.leanapp.cn提供的API](http://musiclake.leanapp.cn%E6%8F%90%E4%BE%9B%E7%9A%84API) service来请求服务吗？
> 还是通过app.native.js直接访问各个音乐服务的？
> 请指教，谢谢

不一样，这个项目的API，同时接了app.native.js 、NeteaseCloudMusicApi、百度音乐的API。
而且这个**app.native.js** 并不是直接访问各个音乐服务，只是用作拼接各个音乐的请求api，网络请求还是用okhttp实现的。
这个项目是从musiclake 中抽离出来的，对于NeteaseCloudMusicApi的API，只是定义了一些接口，并没做具体逻辑。

**Comment by zhougy0717** [comment]
> > 这个项目的API一定要像Music Lake里一样，借助于[http://musiclake.leanapp.cn提供的API](http://musiclake.leanapp.cn%E6%8F%90%E4%BE%9B%E7%9A%84API) service来请求服务吗？
> > 还是通过app.native.js直接访问各个音乐服务的？
> > 请指教，谢谢
> 
> 不一样，这个项目的API，同时接了app.native.js 、NeteaseCloudMusicApi、百度音乐的API。
> 而且这个**app.native.js** 并不是直接访问各个音乐服务，只是用作拼接各个音乐的请求api，网络请求还是用okhttp实现的。
> 这个项目是从musiclake 中抽离出来的，对于NeteaseCloudMusicApi的API，只是定义了一些接口，并没做具体逻辑。

你的意思是，NeteaseCloudMusicApi还需要自己搭建host来提供API service？类似于http://musiclake.leanapp.cn？

**Comment by caiyonglong** [comment]
> > > 这个项目的API一定要像Music Lake里一样，借助于[http://musiclake.leanapp.cn提供的API](http://musiclake.leanapp.cn%E6%8F%90%E4%BE%9B%E7%9A%84API) service来请求服务吗？
> > > 还是通过app.native.js直接访问各个音乐服务的？
> > > 请指教，谢谢
> > 
> > 
> > 不一样，这个项目的API，同时接了app.native.js 、NeteaseCloudMusicApi、百度音乐的API。
> > 而且这个**app.native.js** 并不是直接访问各个音乐服务，只是用作拼接各个音乐的请求api，网络请求还是用okhttp实现的。
> > 这个项目是从musiclake 中抽离出来的，对于NeteaseCloudMusicApi的API，只是定义了一些接口，并没做具体逻辑。
> 
> 你的意思是，NeteaseCloudMusicApi还需要自己搭建host来提供API service？类似于[http://musiclake.leanapp.cn？](http://musiclake.leanapp.cn%EF%BC%9F)

- 嗯，是的。我是搭建在leancloud 上，免费版有使用时间限制

**Comment by zhougy0717** [comment]
你觉得有可能，直接通过retrofit发送HTTP request来从官方链接获得service吗？

**Comment by caiyonglong** [comment]
> 你觉得有可能，直接通过retrofit发送HTTP request来从官方链接获得service吗？

也可以自己拼接url，不依赖js，然后retrofit请求数据
